### ISSUE TITLE
Vital Strike and Ghost Touch Weapons

### ISSUE THREAD

**Issue by bharathrajaram** [Vek17/WrathMods-TabletopTweaks#120] opened 2021-09-25 19:14 UTC
With the change to Vital Strike, it is incorrectly handling ghost touch and incorporeal enemies correctly. Since the damage component has been split into two (to prevent the critical strike issue), the first component of the damage is correctly benefitting from ghost touch and not dealing 0.5x damage versus incorporeal enemies. However the second component of the damage is being modified by the 0.5x for having no ghost touch. 

![image](https://user-images.githubusercontent.com/44509664/134783606-fafb6837-4de5-4084-9677-9dab55a135e1.png)

Expected Behavior: Since Vital Strike is a single hit, the whole hit should correctly inherit the ghost touch property.

**Comment by Vek17** [comment] 2021-09-25 20:09
hm, looking at this it is a bit more complicated to resolve than I hopped, this may take a bit

**Comment by Amariithynar** [comment] 2021-09-26 04:29
Oh my god, is this why precision damage isn't inheriting weapon effects too? @Vek17 I've been dealing with this with the gargoyles with a throwing axe Wenduag build, and just was eating all the damage reduction to the precision damage from her sneak attacks making the fight way harder than it should have been even with her weapons properly aligned and enchanted.

**Comment by Vek17** [comment] 2021-09-26 19:24
Yes it is the same problem, which is part of what makes the solution somewhat complex to do "correctly"

**Comment by Vek17** [comment] 2021-09-27 04:37
Testing a potential fix, initally looks good though, just need to make sure there are no huge regressions elsewhere.
![image](https://user-images.githubusercontent.com/2959420/134846108-915dc7ec-4a74-4cf1-a406-0b561bddaa98.png)

**Comment by Amariithynar** [comment] 2021-09-27 04:46
Awesome! Really glad to hear, Vek! Thank you so much for everything you've been doing; it's appreciated. :)

**Comment by Vek17** [comment] 2021-09-28 03:27
There is an experimental fix for this in the latest release. If you see anything weird let me know

**Comment by Amariithynar** [comment] 2021-09-28 11:25
So far seems to be working well mostly @Vek17, but I did notice that my Eye for an Eye shortbow (+3, composite) is no longer getting its special effect of a bonus 1d12 piercing damage on every hit, only dealing base damage formula for a +3 composite shortbow.

**Closed** 2022-01-10 00:50 UTC
Labels: bug
