### ISSUE TITLE
Spell Quickslots selection hidden.

### ISSUE THREAD

**Issue by GFreenD** [Vek17/WrathMods-TabletopTweaks#146] opened 2021-09-29 21:40 UTC
**Describe the bug**

you cant select any characters spell slots anymore (they are just not there/dont exist) that should have them they suddenly dont and if i select fighter and then select mage, then mage inherit fighter ability and quickslot tabs.
i also cant make my cantrips to be set as used at all times (rightclick) does nothing otherwise it ues skills normaly.

**To Reproduce**
 updated 1.1.2 to 1.3.6 table top tweaks
 updated 1.3.7 to  1.3.14 toybox (not the reason why its crashing already tested all other mods i have)

**Expected behavior**
to assign a spell from spell quickslot bag to a skil bar for a quick use 
.

**Comment by Vek17** [comment] 2021-09-29 23:03
Can you upload a save file where this is taking place? As far as I can reproduce this is no longer an issue

**Comment by Lord451125** [comment] 2021-09-29 23:42
This sounds exactly like what was happening to me here: https://github.com/Vek17/WrathMods-TabletopTweaks/issues/145

Followed this and it worked.

**Comment by Vek17** [comment] 2021-09-29 23:57
And you are 100% on 1.3.6? Because this was fixed in 1.3.6

**Closed** 2022-01-10 00:58 UTC
Labels: bug
